app = "whack-a-mole"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"

  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [services.ports.0.sticky_sessions]
    enabled = true

[env]
  NODE_ENV = "production"
  DATABASE_URL = "your-database-url"